---
title: "Class 04: Data Structures and Data Importing in R"
author: "Marina Erceg"
date: "2026-09-02"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true 
    code_download: true 
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r crash_by_day_vec}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day[2]                      # one position
```

```{r crash_by_name}
crashes_by_day["Fri"]   

crashes_by_day[c(2,4)]
```

```{r crashes_by_condition}
crashes_by_day[crashes_by_day > 2300]  # by condition
```

# Tibble 

```{r crashes_tibble}
crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000)
crashes_df                     # one column, as a vector

dplyr::glimpse(crashes_df)  # equivalent of stf() but prints neater
```

```{r crashes_tibble_name}
crashes_df[["crashes"]]                # the same vector, by name
```

```{r crashes_tibble_condition}
crashes_df[1:2, c("day", "crashes")]   # rows 1 to 2, two columns
```

# examining a job ad 
```{r job_ad}
job = list(
  title   = "Research Data Scientist, Magic Eye",
  company = "Google",
  salary  = list(min = 147000, max = 210000)
)
str(job)

dplyr::glimpse(job)

# Activity in class

#1. The company name.
company_name = job$company #job[[2]]; however, this returns a list job[2]
company_name_as_named_list = job[2] # we typically do not want that as answer
#2. The maximum salary.
max_salary = job$salary$max
#3. The maximum salary again, using only [[ ]].
job[[3]][[2]]
#4. The names of the elements in job.
names(job)
```

# Subsetting

## Vector

- You can subset by a position (i.e, a number) or by name if it is a named vector; 
- You can also pass a vector (e.g., logical condition 2:4 or c(,) ) for subsetting the vector

```{r}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day[2:4] # you can give consecutive numbers 
crashes_by_day[c('Mon','Fri')] # crashes_by_day[c(1,5)]
```

# Jobs 

```{r jobs}
oh_jobs = readr::read_csv(
file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01"
)
```

```{r jobs_base}
oh_jobs_base_r = read.csv(
  file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01"
)
```

```{r check}
dplyr::glimpse(oh_jobs)
dplyr::glimpse(oh_jobs_base_r)
```
